// Code generated by "stringer -output=stringer.go -type=Tag"; DO NOT EDIT.

package asn1

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BOOLEAN-1]
	_ = x[INTEGER-2]
	_ = x[BIT_STRING-3]
	_ = x[OCTET_STRING-4]
	_ = x[NULL-5]
	_ = x[OBJECT_IDENTIFIER-6]
	_ = x[ENUM-10]
	_ = x[UTF8String-12]
	_ = x[RelativeOID-13]
	_ = x[SEQUENCE-48]
	_ = x[SET-49]
	_ = x[PrintableString-19]
	_ = x[T61String-20]
	_ = x[IA5String-22]
	_ = x[UTCTime-23]
	_ = x[GeneralizedTime-24]
	_ = x[GeneralString-27]
}

const (
	_Tag_name_0 = "BOOLEANINTEGERBIT_STRINGOCTET_STRINGNULLOBJECT_IDENTIFIER"
	_Tag_name_1 = "ENUM"
	_Tag_name_2 = "UTF8StringRelativeOID"
	_Tag_name_3 = "PrintableStringT61String"
	_Tag_name_4 = "IA5StringUTCTimeGeneralizedTime"
	_Tag_name_5 = "GeneralString"
	_Tag_name_6 = "SEQUENCESET"
)

var (
	_Tag_index_0 = [...]uint8{0, 7, 14, 24, 36, 40, 57}
	_Tag_index_2 = [...]uint8{0, 10, 21}
	_Tag_index_3 = [...]uint8{0, 15, 24}
	_Tag_index_4 = [...]uint8{0, 9, 16, 31}
	_Tag_index_6 = [...]uint8{0, 8, 11}
)

func (i Tag) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _Tag_name_0[_Tag_index_0[i]:_Tag_index_0[i+1]]
	case i == 10:
		return _Tag_name_1
	case 12 <= i && i <= 13:
		i -= 12
		return _Tag_name_2[_Tag_index_2[i]:_Tag_index_2[i+1]]
	case 19 <= i && i <= 20:
		i -= 19
		return _Tag_name_3[_Tag_index_3[i]:_Tag_index_3[i+1]]
	case 22 <= i && i <= 24:
		i -= 22
		return _Tag_name_4[_Tag_index_4[i]:_Tag_index_4[i+1]]
	case i == 27:
		return _Tag_name_5
	case 48 <= i && i <= 49:
		i -= 48
		return _Tag_name_6[_Tag_index_6[i]:_Tag_index_6[i+1]]
	default:
		return "Tag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
